name = "HTMLBuilder"
uuid = "0cf4c2ae-3c55-4387-8def-d33f99d13a02"
authors = ["Dr Rafael Bailo <Dr.Rafael.Bailo@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
