N = 20

Fibonacci(n::Int) = (n <= 2) ? (1) : (Fibonacci(n - 1) + Fibonacci(n - 2))

HTMLDoc(
  DOCTYPE(),
  html(
    (; lang = "en"),
    head(title("Fibonacci Numbers")),
    body(
      h1("Fibonacci Numbers"),
      h2("Automatically generated by Julia"),
      p("Here are the first $N Fibonacci numbers:"),
      ul([li(string(Fibonacci(n))) for n ∈ 1:N]),
    ),
  ),
)
